version: '3'

services:
  web:
    build: ./app
    ports:
      - "9800:9800"
    depends_on:
      - cache
      - database
  cache:
    image: "redis:alpine"
  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:

